name: Leseansicht - files 2761–2999

on:
  workflow_dispatch

jobs:
  makepdf:
    name: Convert LaTeX to PDF
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Install ANT, LaTeX Things
      run: |
        sudo apt-get update && sudo apt-get install texlive-xetex texlive-humanities texlive-lang-german texlive-lang-french texlive-lang-english texlive-lang-greek openjdk-11-jre-headless ant -y
    - name: Clone private repository with fonts and symbols
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
          owner: 'arthur-schnitzler'
          repository: 'schnitzler-briefe-tex-private-files'
          access-token: ${{ secrets.SCHNITZLER_TEX_PRIVATE }}
    - name: Convert Files
      run: |
        cd tex-leseansicht
        for i in L0{2761..2999}.tex; do
          if [ -f "$i" ]; then
            xelatex $i -interaction=nonstopmode
          else
            echo "File $i not found. Skipping."
          fi
        done
        cd ..
    - name: Create Index
      run: |
        cd tex-leseansicht
        for i in L0{2761..2999}.tex; do
          if [ -f "$i" ]; then
            xelatex $i -interaction=nonstopmode
          else
            echo "File $i not found. Skipping."
          fi
        done
        cd ..
    - name: Final conversion
      run: |
        cd tex-leseansicht
        for i in L0{2761..2999}.tex; do
          if [ -f "$i" ]; then
            xelatex $i -interaction=nonstopmode
          else
            echo "File $i not found. Skipping."
          fi
        done
        cd ..
    - name: copy pdf to pdf-folder
      run: |
        mv ./tex-leseansicht/*.pdf ./pdf-leseansicht/
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: made pdfs
        file_pattern: "*.pdf"
