name: Convert the latest files via XeLaTeX to PDF

on:
  workflow_dispatch
jobs:
  makepdf:
    name: Convert XeLaTeX to PDF
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Install ANT,  LaTeX Things
      run: |
        sudo apt-get update && sudo apt-get install texlive-xetex texlive-humanities texlive-lang-german texlive-lang-french texlive-lang-english texlive-lang-greek  openjdk-11-jre-headless ant -y
    - name: Clone GuillaumeFalourd/formulas-training PRIVATE repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'arthur-schnitzler'
          repository: 'schnitzler-briefe-tex-private-files'
          access-token: ${{ secrets.SCHNITZLER_TEX_PRIVATE }}
    - name: Convert Files
      run: |
        cd tex
        for i in L02600.tex; do xelatex $i -interaction=nonstopmode;done
        for i in L02600.tex; do xelatex $i -interaction=nonstopmode;done
        for i in L02600.tex; do xelatex $i -interaction=nonstopmode;done
        cd ..
    - name: copy pdf to pdf-folder
      run: |
        mv ./tex/*.pdf ./pdf 
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: made a few pdfs
        file_pattern: "*.pdf"
