name: Clone Private Repository Workflow

on:
  push:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
    
  job-public-repo-ubuntu:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone GuillaumeFalourd/formulas-training PRIVATE repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'arthur-schnitzler'
          repository: 'schnitzler-briefe-tex-private-files'
          access-token: ${{ secrets.SCHNITZLER_TEX_PRIVATE }}
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          cd 'schnitzler-briefe-tex-private-files'
          ls -la
          echo "CLONED REPO"
          ls -la

