name: Convert LaTeX to PDF

on:
  workflow_dispatch
jobs:
  makepdf:
    name: Convert LaTeX to PDF
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Install ANT,  LaTeX Things
      run: |
        sudo apt-get update && sudo apt-get install texlive-xetex texlive-humanities texlive-lang-german texlive-lang-french texlive-lang-english texlive-lang-greek  openjdk-11-jre-headless ant -y
    - name: Remove File
      uses: JesseTG/rm@v1.0.0
      with: 
        path: /pdf/*.pdf
    - name: compile latex
      uses: xu-cheng/latex-action@v2
      with:
        latexmk_use_xelatex: true
        work_in_root_file_dir: /tex
    - name: commit result pdf    
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        repository: .
        commit_user_name: martinantonmueller
        commit_user_email: martin.anton.mueller@oeaw.ac.at
        commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

