name: Convert LaTeX to PDF

on:
  workflow_dispatch
jobs:
  makepdf:
    name: Convert LaTeX to PDF
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Install ANT,  LaTeX Things
      run: |
        sudo apt-get update && sudo apt-get install openjdk-11-jre-headless ant -y
    - name: Convert Files
      run: |
        ./makepdf.sh
